Repository Resumates/Resumates, pull requests merged in 2024-07, with the labels that each got.

#80 [ 🎨 Style / 🔧 Fix / ♻️ Refactor ] Header 컴포넌트 수정 및 회원가입 API 분리
  client/src/api/authAPI.jsx
  client/src/api/commonAPI.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Header/HeaderStyle.jsx
  client/src/components/Header/NavLinks.jsx
  client/src/components/Modal/ModalUser.jsx
  client/src/components/Navigation/MainHeader.jsx
  client/src/components/Navigation/MainHeaderStyle.jsx
  client/src/components/Navigation/MainNavigation.jsx
  client/src/components/Navigation/NavLinks.jsx
  client/src/hooks/useSignup.js
  client/src/router/AppRoutes.js
Labels: ♻️ 리팩토링, ✅ 완료, 🎨 스타일

#84 [ 🚀 Feat ] 이력서 상세페이지 API 연결
  client/src/api/commonAPI.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Header/HeaderStyle.jsx
  client/src/components/Header/NavLinks.jsx
  client/src/components/Modal/ModalUser.jsx
  client/src/pages/resume/ResumeDetail.jsx
  client/src/router/AppRoutes.js
Labels: ✅ 완료

#86 [ 🚀 Feat ] 이력서 템플릿 데이터 출력
  client/src/components/Header/NavLinks.jsx
  client/src/pages/resume/ResumeDetail.jsx
  client/src/pages/resume/ResumeSimple.jsx
Labels: ✅ 완료

#87 Feat: Casual 레이아웃 이력서 템플릿
  client/src/asset/profile/blank-profile.webp
  client/src/components/resumeTamplate/CasualLine.jsx
  client/src/components/resumeTamplate/CasualResume.jsx
  client/src/components/resumeTamplate/CasualResumeStyle.jsx
Labels: 🚀 기능추가, 🎨 스타일, 🚀 진행중

#88 [🎨 Style ] MainLogin 페이지 생성
  client/src/components/common/resume/NormalResume.jsx
  client/src/pages/home/mainLogin.jsx
  client/src/router/AppRoutes.js
  client/src/style/MainLoginStyle.jsx
Labels: ✅ 완료

#89 Refactor: Casual 필드 데이터 수정
  client/src/components/resumeTamplate/CasualLine.jsx
  client/src/components/resumeTamplate/ResumeCasual.jsx
  client/src/components/resumeTamplate/ResumeCasualStyle.jsx
Labels: ♻️ 리팩토링, 🎨 스타일, 🚀 진행중

#90 Feat: 이력서 작성 폼
  client/src/components/resumeForm/InputField.jsx
  client/src/pages/resume/CreateResume.jsx
  client/src/style/CreateResumeStyle.jsx
Labels: 🚀 기능추가, 🎨 스타일, 🚀 진행중

#91 [🎨 Style ] MainLogin 페이지 스타일 적용
  client/src/components/common/input.jsx
  client/src/pages/auth/Login.jsx
  client/src/pages/resume/ResumeSimple.jsx
  client/src/style/InputStyle.jsx
  client/src/style/LoginStyle.jsx
  client/src/style/MainLoginStyle.jsx
Labels: 🎨 스타일

#92 [ 🚀 Feat / 🎨 Style ] 로그아웃 모달 및 기능 구현
  client/src/asset/images/icon-logout.png
  client/src/asset/images/icon-userset.png
  client/src/components/Header/HeaderStyle.jsx
  client/src/components/Header/NavLinks.jsx
  client/src/components/Modal/ModalLogout.jsx
  client/src/components/Modal/ModalUser.jsx
  client/src/hooks/hookAuth.js
  client/src/pages/resume/ResumeSimple.jsx
  client/src/router/AppRoutes.js
Labels: ✅ 완료, 🚀 기능추가

#93 [🚀 Feat / 🎨 Style] 이력서 템플릿 생성 및 style 적용
  client/src/asset/images/icon-birth.png
  client/src/asset/images/icon-email.png
  client/src/asset/images/icon-home.png
  client/src/asset/images/icon-phone.png
  client/src/components/resumeTamplate/ResumeSimple.jsx
  client/src/components/resumeTamplate/ResumeSimpleStyle.jsx
  client/src/pages/resume/ResumeDetail.jsx
  client/src/pages/resume/ResumeSimple.jsx
Labels: ✅ 완료, 🎨 스타일

#94 Refactor: 이력서 템플릿 gender필드 수정
  client/src/components/resumeForm/InputField.jsx
  client/src/pages/resume/CreateResume.jsx
  client/src/style/CreateResumeStyle.jsx
Labels: ♻️ 리팩토링, 🚀 진행중

#96 [🚀 Feat] 비밀번호 확인 모달창 추가
  client/src/asset/images/icon-close.png
  client/src/components/Modal/ModalPasswordConfirm.jsx
  client/src/components/account/EditAccountStyle.jsx
  client/src/components/account/EditUserInfo.jsx
  client/src/components/account/EditUserPassword.jsx
  client/src/pages/user/Account.jsx
  client/src/style/AccountStyle.jsx
Labels: ✅ 완료

#104 [🎨 Style ] MyPage UI 수정
  client/src/components/resumeTamplate/ResumeNormal.jsx
  client/src/components/resumeTamplate/ResumeNormalStyle.jsx
  client/src/pages/resume/ResumeDetail.jsx
  client/src/pages/user/Mypage.jsx
  client/src/style/MyPageStyle.jsx
  server/controllers/mypageController.js
  server/routes/myPageRouter.js
Labels: ✅ 완료

#105 [ 🚀 Feat ] 비밀번호 확인 API 추가, 확인 기능 구현
  client/src/api/APIRoutes.js
  client/src/api/authAPI.jsx
  client/src/components/Modal/ModalPasswordConfirm.jsx
  client/src/components/Modal/ModalStyle.jsx
  client/src/components/Modal/ModalUser.jsx
  client/src/components/account/EditUserInfo.jsx
  client/src/pages/user/SetEmail.jsx
  client/src/router/AppRoutes.js
  server/controllers/commonController.js
  server/controllers/usersController.js
  server/routes/userRoute.js
  server/server.js
Labels: ✅ 완료

#107 [🚀 Feat ] Mypage server 연결
  client/src/pages/user/Mypage.jsx
  client/src/router/AppRoutes.js
  server/controllers/mypageController.js
  server/routes/myPageRouter.js
  server/routes/userRoute.js
Labels: 🚀 진행중

#109 🚀 Feat ] Resume model 수정
  server/models/resumes.js
Labels: 🚀 진행중

#111 [ 🔧 Fix ] 마이페이지 API 연결
  client/src/api/APIRoutes.js
  client/src/api/authAPI.jsx
  client/src/api/commonAPI.jsx
  client/src/components/Header/NavLinks.jsx
  client/src/components/Modal/ModalUser.jsx
  client/src/components/account/EditAccountStyle.jsx
  client/src/components/account/EditEmail.jsx
  client/src/hooks/useSignup.js
  client/src/pages/user/Account.jsx
  client/src/pages/user/Mypage.jsx
  client/src/pages/user/SetEmail.jsx
  client/src/router/AppRoutes.js
  server/controllers/commonController.js
  server/controllers/mypageController.js
  server/routes/commonRouter.js
  server/routes/userRoute.js
Labels: ✅ 완료

#112 [🚀 Feat ] 이메일 변경 기능 추가
  client/src/api/APIRoutes.js
  client/src/api/authAPI.jsx
  client/src/components/account/EditEmail.jsx
  client/src/hooks/useSignup.js
  client/src/pages/user/SetEmail.jsx
  server/controllers/usersController.js
  server/routes/userRoute.js
Labels: ✅ 완료, 🚀 기능추가

#113 [🚀 Feat] 비밀번호 재설정 기능 추가
  client/src/api/authAPI.jsx
  client/src/components/account/EditAccountStyle.jsx
  client/src/components/account/EditEmail.jsx
  client/src/components/account/EditUserPassword.jsx
  client/src/hooks/useSignup.js
  client/src/pages/user/SetEmail.jsx
  server/controllers/usersController.js
Labels: 🚀 진행중

#114 Refactor: 이력서 작성 템플릿 데이터
  client/src/components/resumeForm/InputField.jsx
  client/src/data/profileInfoData.js
  client/src/pages/resume/CreateResume.jsx
  client/src/style/CreateResumeStyle.jsx
Labels: ♻️ 리팩토링, 🎨 스타일, 🚀 진행중

#118 Refactor : 마이페이지 이력서 템플릿 선택
  client/src/asset/images/icon-addCircle.svg
  client/src/components/common/AddButton.jsx
  client/src/components/resumeForm/InputField.jsx
  client/src/data/profileInfoData.js
  client/src/pages/resume/CreateResume.jsx
  client/src/pages/user/Mypage.jsx
  client/src/style/CreateResumeStyle.jsx
Labels: ♻️ 리팩토링, ✅ 완료, 🎨 스타일, 🔧 수정

#119 [ 🚀 Feat ] 비밀번호 재설정 예외처리 추가
  client/src/components/account/EditAccountStyle.jsx
  client/src/components/account/EditUserPassword.jsx
  client/src/hooks/useSignup.js
  server/controllers/usersController.js
Labels: ✅ 완료

#121 Style: 마이페이지 UI 수정
  client/src/pages/user/Mypage.jsx
  client/src/style/MyPageStyle.jsx
Labels: 🚀 진행중

#124 [ 🚀 Feat ] 이력서 미리보기 기능 추가
  client/src/api/APIRoutes.js
  client/src/api/commonAPI.jsx
  client/src/api/resumeAPI.jsx
  client/src/components/mypage/MyResumeList.jsx
  client/src/components/mypage/ResumePreview.jsx
  client/src/components/resumeTamplate/CasualLine.jsx
  client/src/components/resumeTamplate/ResumeCasual.jsx
  client/src/components/resumeTamplate/ResumeCasualStyle.jsx
  client/src/components/resumeTamplate/ResumeSimpleStyle.jsx
  client/src/pages/resume/ResumeDetail.jsx
  client/src/pages/user/Mypage.jsx
  client/src/router/AppRoutes.js
  client/src/style/MyPageStyle.jsx
  server/controllers/commonController.js
Labels: ✅ 완료, 🔧 수정

#126 [🚀 Feat ] 이력서 삭제, 인쇄 기능 추가
  client/package-lock.json
  client/package.json
  client/src/api/APIRoutes.js
  client/src/api/resumeAPI.jsx
  client/src/components/mypage/MyResumeList.jsx
  client/src/components/mypage/ResumePreview.jsx
  client/src/components/resumeTamplate/ResumeCasual.jsx
  client/src/components/resumeTamplate/ResumeNormal.jsx
  client/src/components/resumeTamplate/ResumeNormalStyle.jsx
  client/src/components/resumeTamplate/ResumeSimple.jsx
  client/src/components/resumeTamplate/ResumeSimpleStyle.jsx
  client/src/pages/user/Mypage.jsx
  client/src/style/MyPageStyle.jsx
  server/controllers/resumeController.js
  server/routes/commonRouter.js
  server/routes/resumeRouter.js
Labels: ✅ 완료

#129 [🚀 Feat ] 네이버 로그인 구현
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/pages/auth/Login.jsx
  client/src/style/InputStyle.jsx
  package-lock.json
  package.json
  server/controllers/commonController.js
  server/controllers/passport.js
  server/models/user.js
  server/node_modules/.package-lock.json
  server/package-lock.json
  server/package.json
  server/routes/authRoutes.js
  server/routes/userRoute.js
  server/server.js
Labels: 🚀 진행중

#130 [ 🗂️ Rename ] 이력서 템플릿 폴더 구조 변경
  client/src/components/mypage/ResumePreview.jsx
  client/src/components/resumeTamplate/A4/CasualLineA4.jsx
  client/src/components/resumeTamplate/A4/ResumeCasualA4.jsx
  client/src/components/resumeTamplate/A4/ResumeCasualA4Style.jsx
  client/src/components/resumeTamplate/A4/ResumeNormalA4.jsx
  client/src/components/resumeTamplate/A4/ResumeNormalA4Style.jsx
  client/src/components/resumeTamplate/A4/ResumeSimpleA4.jsx
  client/src/components/resumeTamplate/A4/ResumeSimpleA4Style.jsx
  client/src/components/resumeTamplate/default/CasualLine.jsx
  client/src/components/resumeTamplate/default/ResumeCasual.jsx
  client/src/components/resumeTamplate/default/ResumeCasualStyle.jsx
  client/src/components/resumeTamplate/default/ResumeNormal.jsx
  client/src/components/resumeTamplate/default/ResumeNormalStyle.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/components/resumeTamplate/default/ResumeSimpleStyle.jsx
Labels: 🔧 수정

#131 Feat: 네이버 로그인 로직 수정
  client/src/pages/auth/Login.jsx
  server/controllers/passport.js
  server/models/user.js
  server/routes/authRoutes.js
Labels: 🚀 진행중

#132 Refator: 이력서 작성 페이지 분기처리
  client/src/components/resumeForm/InputField.jsx
  client/src/data/profileInfoData.js
  client/src/pages/resume/CreateResume.jsx
  client/src/style/CreateResumeStyle.jsx
Labels: ♻️ 리팩토링, 🎨 스타일, 🔧 수정, 🚀 진행중

#135 [🚀 Feat ] Error 페이지 구현
  client/src/asset/images/404Error.png
  client/src/pages/auth/Login.jsx
  client/src/pages/error/Error.jsx
  client/src/router/AppRoutes.js
  client/src/style/ErroStyl.jsx
  server/controllers/passport.js
  server/routes/authRoutes.js
Labels: ✅ 완료

#138 Style: 이력서 작성 레이아웃
  client/src/components/common/AddButton.jsx
  client/src/components/resumeForm/InputField.jsx
  client/src/pages/resume/CreateResume.jsx
  client/src/style/CreateResumeStyle.jsx
Labels: ♻️ 리팩토링, 🎨 스타일, 🚀 진행중

#139 Style: 스킬 추가 버튼
  client/src/components/resumeForm/InputField.jsx
  client/src/pages/resume/CreateResume.jsx
  client/src/style/CreateResumeStyle.jsx
Labels: ♻️ 리팩토링, 🎨 스타일, 🚀 진행중

#140 [ 🚀 Feat ] 템플릿 변경 모달 추가
  client/src/components/resumeTamplate/ChangeTemplate.jsx
  client/src/pages/resume/SampleTemplate.jsx
Labels: 🚀 기능추가

#142 Style: 이력서작성 인적사항 사진 업로드 버튼 UI
  client/src/components/common/AddButton.jsx
  client/src/components/resumeForm/InputField.jsx
  client/src/style/CreateResumeStyle.jsx
Labels: ♻️ 리팩토링, ✅ 완료, 🎨 스타일

#143 Feat: 이력서 작성 스킬 추가 기능
  client/src/components/common/AddButton.jsx
  client/src/components/resumeForm/InputField.jsx
  client/src/pages/resume/CreateResume.jsx
Labels: ♻️ 리팩토링, ✅ 완료, 🚀 기능추가

#144 [ 🎨 Style ] 이미지 크롭 모달 UI 구현
  client/src/components/Header/Header.jsx
  client/src/components/Modal/ModalCropImg.jsx
  client/src/components/Modal/ModalUser.jsx
  client/src/pages/resume/SampleTemplate.jsx
Labels: 🚀 진행중

#145 Refactor: 이력서 작성 추가 UI 기능
  client/src/components/resumeForm/InputField.jsx
  client/src/data/profileInfoData.js
  client/src/pages/resume/CreateResume.jsx
  client/src/style/CreateResumeStyle.jsx
Labels: ♻️ 리팩토링, 🚀 기능추가, 🎨 스타일, 🚀 진행중

#146 [ 🚀 Feat ] 이미지 크롭 모달 연결
  client/package-lock.json
  client/package.json
  client/src/components/Modal/ModalCropImg.jsx
  client/src/components/resumeForm/InputField.jsx
Labels: 🚀 진행중

#147 Refactor: 이력서 작성 메뉴,컨텐츠 컴포넌트 분리
  client/src/components/resumeForm/ContentItem.jsx
  client/src/components/resumeForm/InputField.jsx
  client/src/components/resumeForm/ResumeMenu.jsx
  client/src/pages/resume/CreateResume.jsx
Labels: ♻️ 리팩토링, 🎨 스타일, 🔧 수정, 🚀 진행중

#150 [ 🚀 Feat ] 템플릿 변경 컴포넌트 연결, UI 수정
  client/src/components/resumeTamplate/ChangeTemplate.jsx
  client/src/pages/resume/CreateResume.jsx
  client/src/pages/resume/SampleTemplate.jsx
  client/src/pages/resume/TemplateList.jsx
  client/src/style/TemplateListStyle.jsx
  server/upload/profileImg.png
Labels: ✅ 완료

#151 Style: 이력서 작성 추가버튼 간격조절
  client/src/components/common/AddButton.jsx
  client/src/components/resumeForm/ContentItem.jsx
  client/src/style/CreateResumeStyle.jsx
Labels: 🎨 스타일, 🔧 수정, 🚀 진행중

#152 [ 🚀 Feat ] 이력서 유저정보 컴포넌트 분리
  client/src/components/resumeForm/UserInfo.jsx
  client/src/components/resumeTamplate/default/ResumeCasual.jsx
  client/src/components/resumeTamplate/default/ResumeNormal.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/data/profileInfoData.js
  client/src/pages/resume/CreateResume.jsx
  client/src/pages/resume/SampleTemplate.jsx
  client/src/router/AppRoutes.js
  client/src/style/CreateResumeStyle.jsx
  server/server.js
  server/upload/profileImg.png
Labels: 🚀 진행중

#157 Feat: 이력서 작성 페이지 콘텐츠 삭제버튼
  client/src/asset/images/icon-deleteBtn.svg
  client/src/components/common/DeleteButton.jsx
  client/src/components/resumeForm/ContentItem.jsx
  client/src/pages/resume/CreateResume.jsx
Labels: ✅ 완료, 🚀 기능추가, 🎨 스타일

#158 Refactor: 템플릿 내용 출력
  client/src/components/resumeForm/ContentItem.jsx
  client/src/components/resumeForm/InputField.jsx
  client/src/pages/resume/CreateResume.jsx
Labels: ♻️ 리팩토링, 🎨 스타일, 🚀 진행중

#160 [🚀 Feat ] 포토폴리오 url 컴포넌트 생성
  client/src/components/resumeForm/PortofolioInfo.jsx
  client/src/router/AppRoutes.js
  server/server.js
Labels: 🚀 진행중

#161 [ ♻️ Refactor ] 유저 정보 컴포넌트 분리
  client/src/components/Modal/ModalCrop.jsx
  client/src/components/resumeForm/InputField.jsx
  client/src/components/resumeForm/UserInfo.jsx
  client/src/pages/resume/CreateResume.jsx
  client/src/pages/resume/SampleTemplate.jsx
  client/src/style/CreateResumeStyle.jsx
  client/src/utils/ImageCropper.jsx
  server/upload/profileImg.png
Labels: ♻️ 리팩토링

#162 Refactor: 이력서작성페이지 템플릿 출력값
  client/src/components/resumeForm/ContentItem.jsx
  client/src/components/resumeForm/InputField.jsx
Labels: ♻️ 리팩토링, 🚀 진행중

#163 [ 🚀 Feat ] 인적사항 화면 출력
  client/src/components/resumeForm/ContentItem.jsx
  client/src/components/resumeForm/InputField.jsx
  client/src/components/resumeForm/UserInfo.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/data/profileInfoData.js
  client/src/pages/resume/CreateResume.jsx
  client/src/style/CreateResumeStyle.jsx
  server/upload/profileImg.png
Labels: 🚀 진행중

#164 [🚀 Feat ] 인적사항 컴포넌트 템플릿 연결
  client/src/components/Modal/ModalCrop.jsx
  client/src/components/resumeForm/UserInfo.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/components/resumeTamplate/default/ResumeSimpleStyle.jsx
  client/src/pages/resume/CreateResume.jsx
  client/src/style/CreateResumeStyle.jsx
  client/src/utils/ImageCropper.jsx
  server/upload/profileImg.png
Labels: ✅ 완료

#165 [ 🚀 Feat ]경력 컴포넌트 분리
  client/src/components/resumeForm/UserInfo.jsx
  client/src/components/resumeForm/WorkExperience.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/data/profileInfoData.js
  client/src/pages/resume/CreateResume.jsx
Labels: 🚀 진행중

#166 [ 🚀 Feat ]경력 컴포넌트 템플릿 출력
  client/src/components/resumeForm/WorkExperience.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/pages/resume/CreateResume.jsx
  server/upload/profileImg.png
Labels: ✅ 완료

#168 [🚀 Feat ] 이력서 포토폴리오 컴포넌트 생성
  client/src/components/resumeForm/PortfolioSection.jsx
  client/src/components/resumeForm/PortofolioInfo.jsx
  client/src/components/resumeForm/SkillsSection.jsx
  client/src/pages/resume/CreateResume.jsx
  client/src/router/AppRoutes.js
  server/upload/profileImg_BASE_787.png
  server/upload/profileImg_LOCAL_787.png
  server/upload/profileImg_REMOTE_787.png
Labels: 🚀 진행중

#170 [🚀 Feat ] 이력서 Skill 컴포넌트 수정
  client/src/components/resumeForm/PortfolioSection.jsx
  client/src/components/resumeForm/SkillsSection.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/pages/resume/CreateResume.jsx
Labels: 🚀 진행중

#171 [ 🚀 Feat ] 이력서 제목 컴포넌트 추가
  client/src/components/Modal/ModalCrop.jsx
  client/src/components/resumeForm/ResumeTitle.jsx
  client/src/components/resumeForm/UserInfo.jsx
  client/src/components/resumeForm/WorkExperience.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/pages/resume/CreateResume.jsx
  server/upload/profileImg.png
Labels: ✅ 완료

#172 [ ♻️ Refactor / 🔧 Fix ] input 영역 코드 분리, Header UI 수정
  client/src/components/Header/Header.jsx
  client/src/components/Header/HeaderStyle.jsx
  client/src/components/resumeForm/UserInfo.jsx
  client/src/components/resumeForm/UserInfoInput.jsx
  client/src/components/resumeForm/WorkExperience.jsx
  client/src/components/resumeForm/WorkInput.jsx
  client/src/style/GlobalStyle.jsx
  server/upload/profileImg.png
Labels: ✅ 완료

#173 [🔧Fix ] 이력서 Skill 컴포넌트 수정
  client/src/components/resumeForm/PortfolioSection.jsx
  client/src/components/resumeForm/SkillsSection.jsx
  client/src/pages/resume/CreateResume.jsx
Labels: 🔧 수정

#175 [ 🚀 Feat ] 계정 삭제 기능 구현
  client/src/api/APIRoutes.js
  client/src/api/authAPI.jsx
  client/src/components/Header/HeaderStyle.jsx
  client/src/components/Modal/ModalDelete.jsx
  client/src/components/Modal/ModalStyle.jsx
  client/src/components/account/EditUserInfo.jsx
  client/src/components/mypage/ResumePreview.jsx
  server/controllers/resumeController.js
  server/controllers/usersController.js
  server/routes/userRoute.js
  server/upload/profileImg.png
  server/upload/profileImg_BASE_787.png
  server/upload/profileImg_LOCAL_787.png
  server/upload/profileImg_REMOTE_787.png
Labels: ✅ 완료, 🚀 기능추가

#178 [🔧 Fix ] Normal 템플릿 수정
  client/src/components/resumeTamplate/default/ResumeNormal.jsx
  client/src/components/resumeTamplate/default/ResumeNormalStyle.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/pages/resume/SampleTemplate.jsx
Labels: 🔧 수정

#179 Refactor: 경력, 어학 템플릿 기능
  client/src/components/resumeForm/Activity.jsx
  client/src/components/resumeForm/Qualification.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/pages/resume/CreateResume.jsx
  server/models/resumes.js
  server/upload/profileImg.png
Labels: ♻️ 리팩토링, 🎨 스타일, 🚀 진행중

#180 Fix: 이력서 기술 컴포넌트 수정
  client/src/components/resumeForm/SkillsSection.jsx
  client/src/pages/resume/SampleTemplate.jsx
Labels: 🔧 수정

#181 [🔧 Fix ]이력서 skill 컴포넌트 수정
  client/src/components/resumeForm/SkillsSection.jsx
  client/src/pages/resume/CreateResume.jsx
Labels: 🔧 수정

#182 Refactor: 자격 어학 데이터 추가
  client/src/components/resumeForm/Activity.jsx
  client/src/components/resumeForm/Qualification.jsx
Labels: ♻️ 리팩토링, 🚀 기능추가, 🎨 스타일, 🚀 진행중

#183 [ 🔧 Fix ] 경험 컴포넌트 실시간 데이터 출력
  client/src/components/resumeForm/SkillsSection.jsx
  client/src/components/resumeForm/WorkExperience.jsx
  client/src/components/resumeTamplate/A4/ResumeCasualA4.jsx
  client/src/components/resumeTamplate/A4/ResumeCasualA4Style.jsx
  client/src/components/resumeTamplate/ChangeTemplate.jsx
  client/src/components/resumeTamplate/default/ResumeCasual.jsx
  client/src/pages/resume/CreateResume.jsx
  client/src/style/TemplateListStyle.jsx
  server/upload/profileImg.png
Labels: 🔧 수정

#185 [🚀 Feat ] 체험하기 페이지 구현하기
  client/src/components/resumeForm/PortfolioSection.jsx
  client/src/components/resumeForm/SkillsSection.jsx
  client/src/components/resumeTamplate/default/ResumeNormal.jsx
  client/src/pages/resume/SampleTemplate.jsx
  server/upload/profileImg.png
Labels: 🚀 진행중

#186 Refactor: 심플템플릿 데이터 출력
  client/src/components/resumeForm/Activity.jsx
  client/src/components/resumeForm/Qualification.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/pages/resume/CreateResume.jsx
Labels: ♻️ 리팩토링, 🎨 스타일, 🚀 진행중

#188 [ 🔧 Fix ] casualA4 컴포넌트 데이터 출력
  client/src/asset/images/icon-addr-casual.png
  client/src/asset/images/icon-birth-casual.png
  client/src/asset/images/icon-email-casual.png
  client/src/asset/images/icon-phone-casual.png
  client/src/components/resumeTamplate/A4/CasualLineA4.jsx
  client/src/components/resumeTamplate/A4/ResumeCasualA4.jsx
  client/src/components/resumeTamplate/A4/ResumeCasualA4Style.jsx
Labels: ✅ 완료, 🔧 수정

#189 [🔧 Fix ] 체험하기 페이지 수정
  client/src/pages/resume/SampleTemplate.jsx
Labels: 🔧 수정

#190 Refator: resumes 모델 수정
  server/models/resumes.js
Labels: ♻️ 리팩토링, ✅ 완료, 🔧 수정

#191 Refactor: 이력서작성 사용하지않은 함수제거
  client/src/pages/resume/CreateResume.jsx
Labels: ♻️ 리팩토링, ✅ 완료, 🔧 수정, 🚀 진행중

#193 [ 🚀 Feat ] 이력서 수정페이지 데이터 출력
  client/src/components/Header/NavLinks.jsx
  client/src/components/resumeForm/ResumeTitle.jsx
  client/src/components/resumeForm/SkillsSection.jsx
  client/src/components/resumeForm/UserInfo.jsx
  client/src/components/resumeForm/UserInfoInput.jsx
  client/src/components/resumeForm/WorkExperience.jsx
  client/src/components/resumeForm/WorkInput.jsx
  client/src/components/resumeTamplate/ChangeTemplate.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/components/resumeTamplate/default/ResumeSimpleStyle.jsx
  client/src/pages/resume/EditResume.jsx
  client/src/pages/resume/TemplateList.jsx
  client/src/style/Container.jsx
  client/src/style/CreateResumeStyle.jsx
  client/src/style/GlobalStyle.jsx
  client/src/style/TemplateListStyle.jsx
  server/upload/profileImg.png
Labels: ✅ 완료

#194 Refactor: 이력서작성 저장 DB 연결
  client/package-lock.json
  client/package.json
  client/src/hooks/useResume.js
  client/src/pages/resume/CreateResume.jsx
  server/controllers/resumeController.js
  server/models/resumes.js
  server/server.js
Labels: ♻️ 리팩토링, 🔧 수정, 🚀 진행중

#195 style: Activity 삭제버튼 레이아웃 수정
  client/src/components/resumeForm/Activity.jsx
  client/src/components/resumeForm/Qualification.jsx
Labels: ♻️ 리팩토링, 🎨 스타일, 🔧 수정

#196 [ 🔧 Fix ] 스킬, 포트폴리오 컴포넌트 수정
  client/src/components/resumeForm/PortfolioSection.jsx
  client/src/components/resumeForm/SkillsSection.jsx
  client/src/components/resumeTamplate/default/CasualLine.jsx
  client/src/components/resumeTamplate/default/ResumeCasual.jsx
  client/src/components/resumeTamplate/default/ResumeCasualStyle.jsx
  client/src/pages/resume/CreateResume.jsx
  client/src/pages/resume/EditResume.jsx
  client/src/style/CreateResumeStyle.jsx
  server/upload/profileImg.png
Labels: ✅ 완료

#197 [♻️ Refactor] 체험하기페이지 수정
  client/src/components/resumeTamplate/A4/ResumeNormalA4Style.jsx
  client/src/components/resumeTamplate/default/ResumeNormalStyle.jsx
  client/src/pages/resume/SampleTemplate.jsx
  server/upload/profileImg.png
Labels: ♻️ 리팩토링

#198 [ 🔧 Fix ] 이력서 템플릿 UI 수정 및 데이터 출력
  client/src/components/resumeForm/SkillsSection.jsx
  client/src/components/resumeTamplate/A4/CasualLineA4.jsx
  client/src/components/resumeTamplate/A4/ResumeCasualA4.jsx
  client/src/components/resumeTamplate/A4/ResumeCasualA4Style.jsx
  client/src/components/resumeTamplate/A4/ResumeSimpleA4.jsx
  client/src/components/resumeTamplate/default/CasualLine.jsx
  client/src/components/resumeTamplate/default/ResumeCasual.jsx
  client/src/components/resumeTamplate/default/ResumeCasualStyle.jsx
  client/src/components/resumeTamplate/default/ResumeSimple.jsx
  client/src/components/resumeTamplate/default/ResumeSimpleStyle.jsx
Labels: 🚀 진행중

#199 fix: 이미지 용량 처리 해결
  server/models/resumes.js
  server/server.js
  server/upload/profileImg.png
Labels: ♻️ 리팩토링, ✅ 완료, 🚨에러발견

#200 Feat: 이력서 불러오기 모달생성
  client/public/index.html
  client/src/components/Modal/ModalPortal.jsx
  client/src/pages/resume/CreateResume.jsx
Labels: ♻️ 리팩토링, 🚀 기능추가, 🎨 스타일

#202 [♻️ Refactor ]이력서 simple 컴포넌트 수정
  client/src/components/resumeTamplate/default/ResumeSimpleStyle.jsx
Labels: ♻️ 리팩토링

#203 [ 🚀 Feat ] 이력서 수정 기능 구현
  client/src/api/resumeAPI.jsx
  client/src/components/Modal/ModalCrop.jsx
  client/src/components/resumeForm/Activity.jsx
  client/src/components/resumeForm/PortfolioSection.jsx
  client/src/components/resumeForm/Qualification.jsx
  client/src/components/resumeForm/WorkExperience.jsx
  client/src/components/resumeTamplate/A4/ResumeSimpleA4.jsx
  client/src/components/resumeTamplate/A4/ResumeSimpleA4Style.jsx
  client/src/pages/resume/EditResume.jsx
  client/src/utils/ImageCropper.jsx
  server/controllers/resumeController.js
  server/models/resumes.js
  server/routes/resumeRouter.js
  server/upload/profileImg.png
Labels: ✅ 완료, 🚀 기능추가

#204 Feat: 이력서 작성 내용 불러오기 모달창
  client/src/components/Modal/ModalPortal.jsx
  client/src/pages/resume/CreateResume.jsx
Labels: 🚀 기능추가, 🎨 스타일, 🚀 진행중

#205 [ 🚀 Feat ] 이력서 컴포넌트 스크롤 연결
  client/src/components/resumeForm/Activity.jsx
  client/src/components/resumeForm/PortfolioSection.jsx
  client/src/components/resumeForm/Qualification.jsx
  client/src/components/resumeForm/ResumeMenu.jsx
  client/src/components/resumeForm/ResumeTitle.jsx
  client/src/components/resumeForm/SkillsSection.jsx
  client/src/components/resumeForm/UserInfo.jsx
  client/src/components/resumeForm/WorkExperience.jsx
Labels: ✅ 완료

#206 Refactor: 작성 이력서 없을 경우 예외 처리
  client/src/pages/resume/CreateResume.jsx
Labels: ♻️ 리팩토링, 🚀 기능추가, 🎨 스타일, 🚀 진행중

#207 [ 🔧 Fix ] 이력서 컴포넌트 및 모델 수정
  client/src/components/resumeForm/UserInfo.jsx
  client/src/components/resumeForm/WorkExperience.jsx
  client/src/components/resumeTamplate/A4/ResumeNormalA4.jsx
  client/src/components/resumeTamplate/default/ResumeNormal.jsx
  server/models/resumes.js
Labels: ✅ 완료

#208 Refactor: 이력서 불러오기 네비게이션 기능
  client/src/pages/resume/CreateResume.jsx
Labels: ♻️ 리팩토링, 🚀 기능추가, 🔧 수정, 🚀 진행중

#209 Style: 슬라이드 길이 조절
  client/src/pages/resume/CreateResume.jsx
Labels: ♻️ 리팩토링, 🎨 스타일, 🚀 진행중

#210 [🎨 Style ] Main 화면 수정
  client/src/components/resumeTamplate/A4/ResumeNormalA4.jsx
  client/src/pages/home/Main.jsx
Labels: 🎨 스타일

#211 [♻️ Refactor] normal 컴포넌트 수정
  client/src/components/resumeTamplate/A4/ResumeNormalA4.jsx
  client/src/components/resumeTamplate/default/ResumeNormalStyle.jsx
Labels: ♻️ 리팩토링

#212 [ ♻️ Refactor ] UI 수정 및 불필요한 코드 제거
  client/src/asset/images/ResumeImages.png
  client/src/asset/images/main-left.png
  client/src/asset/images/resumes.png
  client/src/components/Modal/ModalCrop.jsx
  client/src/components/resumeForm/Activity.jsx
  client/src/components/resumeForm/PortfolioSection.jsx
  client/src/components/resumeForm/Qualification.jsx
  client/src/components/resumeForm/WorkExperience.jsx
  client/src/components/resumeTamplate/A4/CasualLineA4.jsx
  client/src/components/resumeTamplate/A4/ResumeCasualA4.jsx
  client/src/components/resumeTamplate/A4/ResumeSimpleA4.jsx
  client/src/components/resumeTamplate/default/ResumeCasual.jsx
  client/src/components/resumeTamplate/default/ResumeNormal.jsx
  client/src/pages/auth/Login.jsx
  client/src/pages/home/Main.jsx
  client/src/pages/home/mainLogin.jsx
  client/src/pages/resume/EditResume.jsx
  client/src/pages/resume/SampleTemplate.jsx
  client/src/router/AppRoutes.js
  client/src/style/InputStyle.jsx
  client/src/style/LoginStyle.jsx
  client/src/style/MainLoginStyle.jsx
  client/src/style/MainPageStyle.jsx
Labels: ♻️ 리팩토링, ✅ 완료

#213 [ 🔧 Fix ] 이미지 형식 수정
  client/src/components/Modal/ModalCrop.jsx
  client/src/utils/ImageCropper.jsx
  server/upload/profileImg.jpeg
Labels: 🔧 수정

#214 [ 🚀 Feat ] 이력서 작성 완료 알림창 추가
  client/src/hooks/useResume.js
  client/src/pages/resume/CreateResume.jsx
Labels: ✅ 완료
