Repository Resumates/Resumates, pull requests merged in 2024-06, with the labels that each got.

#26 [🚀 Feat ] 아이디 검증, 이메일 검증
  client/public/index.html
  client/public/manifest.json
  client/src/index.css
  client/src/pages/auth/Signup.jsx
  client/src/style/GlobalStyle.jsx
  server/controllers/signupController.js
  server/routes/userRoute.js
Labels: ✅ 완료

#27 [🚀 Feat ] 유효성검사 템플릿 생성
  client/package-lock.json
  client/package.json
  client/src/components/common/Navigation.jsx
  client/src/pages/auth/Login.jsx
  client/src/utill/validator.js
Labels: ✅ 완료

#29 [🚀 Feat ] 회원가입 기본 기능 구현
  client/src/pages/auth/Signup.jsx
  client/src/router/AppRoutes.js
  client/src/util/validator.js
  server/controllers/signupController.js
  server/controllers/usersController.js
  server/models/user.js
  server/routes/userRoute.js
Labels: 🚀 기능추가

#36 [ 🎨 Style ] 버튼 컴포넌트 생성
  client/src/api/APIRoutes.js
  client/src/components/common/Button.jsx
  client/src/pages/auth/Signup.jsx
  client/src/utill/validator.js
Labels: ✅ 완료, 🎨 스타일

#38 [🚀 Feat] 공통 컨트롤러, 라우터 생성
  server/controllers/commonController.js
  server/controllers/index.js
  server/controllers/resumeController.js
  server/routes/commonRouter.js
  server/routes/index.js
  server/routes/resumeRouter.js
  server/server.js
Labels: ✅ 완료, 🚀 기능추가

#40 [ 🔧 Fix ] 버튼 콘솔 오류 해결, 회원가입 controller 응답 수정
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/components/common/Button.jsx
  client/src/pages/auth/Signup.jsx
  client/src/utils/sendmail.js
  client/src/utils/validator.js
  package-lock.json
  package.json
  server/controllers/usersController.js
  server/routes/userRoute.js
Labels: ✅ 완료, 🔧 수정

#41 [🚀 Feat ] Header 컴포넌트 생성
  client/src/App.js
  client/src/asset/images/logo.png
  client/src/components/Navigation/MainHeader.jsx
  client/src/components/Navigation/MainHeaderStyle.jsx
  client/src/components/Navigation/MainNavigation.jsx
  client/src/components/Navigation/NavLinks.jsx
  client/src/components/Navigation/NavLinksStyle.jsx
  client/src/components/common/Navigation.jsx
  client/src/components/common/context/auth-context.js
  client/src/pages/auth/Login.jsx
  client/src/router/AppRoutes.js
Labels: ✅ 완료

#45 [🚀 Feat ] 회원가입 인증코드 발송
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/pages/auth/Signup.jsx
  client/src/utils/sendmail.js
  server/.gitignore
  server/controllers/usersController.js
  server/node_modules/.package-lock.json
  server/package-lock.json
  server/package.json
Labels: ✅ 완료, 🚀 기능추가

#46 [♻️ Refactor] PR resume 모델 필드명 및 코드 오타 수정
  server/models/resumes.js
Labels: ♻️ 리팩토링, 🔧 수정

#47 [🚀 Feat ] client 페이지, api router 설정
  client/src/api/APIRoutes.js
  client/src/pages/MainPage.jsx
  client/src/pages/error/Error.jsx
  client/src/pages/home/Main.jsx
  client/src/pages/resume/CreateResume.jsx
  client/src/pages/resume/TemplateList.jsx
  client/src/pages/user/Account.jsx
  client/src/pages/user/Mypage.jsx
  client/src/router/AppRoutes.js
Labels: ✅ 완료

#49 [🚀 Feat ] Login Client 와 Server 연결
  client/src/components/common/context/auth-context.js
  client/src/pages/auth/Login.jsx
  client/src/router/AppRoutes.js
  server/controllers/usersController.js
Labels: ✅ 완료

#51 [🚀 Feat ] token 생성
  client/src/components/common/context/auth-context.js
  client/src/router/AppRoutes.js
  server/controllers/usersController.js
  server/middleware/checkAuth.js
Labels: 🚀 진행중

#52 [🚀 Feat] 이력서 상세 페이지 DB 연결
  server/controllers/commonController.js
  server/controllers/resumeController.js
  server/models/resumes.js
  server/routes/commonRouter.js
Labels: ♻️ 리팩토링, ✅ 완료, 🚀 기능추가

#54 [♻️ Refactor] 이력서 수정 및 삭제기능
  server/controllers/resumeController.js
  server/routes/resumeRouter.js
Labels: ♻️ 리팩토링, ✅ 완료, 🚀 기능추가

#55 [🚀 Feat ] 회원가입 유효성 검사 추가
  client/src/asset/images/resumes.png
  client/src/components/InputBox.jsx
  client/src/components/common/Button.jsx
  client/src/hooks/useSignup.js
  client/src/pages/auth/Signup.jsx
  client/src/router/AppRoutes.js
  client/src/style/SignupStyle.jsx
  server/controllers/usersController.js
Labels: ✅ 완료, 🚀 기능추가

#60 [ 🔧 Fix / 🎨 Style ] 회원가입 스타일 수정
  client/src/hooks/useSignup.js
  client/src/pages/auth/Signup.jsx
  client/src/style/SignupStyle.jsx
  server/controllers/usersController.js
  server/routes/userRoute.js
  server/server.js
Labels: ✅ 완료, 🎨 스타일, 🔧 수정

#61 Refactor: 이력서 작성 birth 필드 수정
  server/controllers/resumeController.js
  server/models/resumes.js
Labels: ♻️ 리팩토링, ✅ 완료

#62 Refactor: PORT, MONGO URL ENV 환경변수로 설정
  server/server.js
Labels: ♻️ 리팩토링, ✅ 완료, 🔧 수정

#63 Hotfix: 이전 코드로 원복
  server/server.js
Labels: ✅ 완료, 🔧 수정

#65 [ 🔧 Fix ] 공통 컨트롤러 수정
  server/controllers/commonController.js
  server/controllers/usersController.js
  server/routes/commonRouter.js
  server/routes/userRoute.js
Labels: ✅ 완료, 🔧 수정

#72 [ 🚀 Feat / 🔧 Fix ] 유저 데이터 API 연결
  client/src/api/APIRoutes.js
  client/src/api/commonAPI.jsx
  client/src/hooks/hookAuth.js
  client/src/pages/resume/TemplateList.jsx
  client/src/pages/user/Account.jsx
  server/controllers/commonController.js
  server/controllers/usersController.js
  server/routes/commonRouter.js
Labels: ✅ 완료, 🔧 수정

#74 [ 🚀 Feat ] 계정관리 페이지 생성
  client/src/api/authAPI.jsx
  client/src/api/commonAPI.jsx
  client/src/components/account/EditUserInfo.jsx
  client/src/components/account/EditUserPassword.jsx
  client/src/pages/user/Account.jsx
Labels: 🚀 진행중

#75 [🎨 Style] 계정관리 이메일 설정, 비밀번호 설정 ui 구현
  client/src/api/commonAPI.jsx
  client/src/asset/images/icon-check.png
  client/src/components/account/EditAccountStyle.jsx
  client/src/components/account/EditUserInfo.jsx
  client/src/components/account/EditUserPassword.jsx
  client/src/pages/auth/Signup.jsx
  client/src/pages/user/Account.jsx
  client/src/style/AccountStyle.jsx
  client/src/style/CommonStyle.jsx
  client/src/style/GlobalStyle.jsx
  client/src/style/SignupStyle.jsx
Labels: ✅ 완료, 🎨 스타일
